# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

[uwsgi]
socket = 0.0.0.0:5000
module = invenio_app.wsgi_ui:application
master = true
die-on-term = true
processes = 2
threads = 2
