# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

# This is the Continuous Integration (Jenkins) server docker-compose file.

version: '2.2'
services:
  # UI + API Application
  app:
    extends:
      file: docker-services.yml
      service: app
    build:
      context: ./
    # Temporarily replace ./run-ci-tests.sh
    # TODO: Fix E2E as separate task
    command: pipenv run ./run-tests.sh
    image: cd2h-repo-project-ci
    # TODO: 'links' are deprecated, use 'networks'
    links:
      - cache
      - es
      - mq
      - db
  cache:
    extends:
      file: docker-services.yml
      service: cache
    ports:
      - "6380:6379"
  db:
    extends:
      file: docker-services.yml
      service: db
    ports:
      - "5433:5432"
  mq:
    extends:
      file: docker-services.yml
      service: mq
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    extends:
      file: docker-services.yml
      service: es
    ports:
      - "9201:9200"
      - "9301:9300"
