# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.2'
services:
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6380:6379"
  db:
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER=cd2h-repo-project"
      - "POSTGRES_PASSWORD=cd2h-repo-project"
      - "POSTGRES_DB=cd2h-repo-project"
    ports:
      - "5433:5432"
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9201:9200"
      - "9301:9300"
  app:
    extends:
      file: docker-services.yml
      service: app
    build:
      context: ./
      args:
        - GITHUB_PRIVATE_TOKEN=${GITHUB_PRIVATE_TOKEN}
    env_file:
      - ci.env
    command: ./run-ci-tests.sh
    image: cd2h-repo-project-ci
    # TODO: 'links' are deprecated, use 'networks'
    links:
      - cache
      - es
      - mq
      - db
