# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.2'
services:
  # Load balancer
  lb:
    extends:
      file: docker-services.yml
      service: lb
    links:
      - frontend
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/opt/cd2h-repo-project/var/instance/static
    links:
      - web-ui
      - web-api
  # UI Application
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    build:
      context: ./
    command: uwsgi /opt/cd2h-repo-project/var/instance/uwsgi_ui.ini
    image: cd2h-repo-project-web-ui
    ports:
      - "5000"
    volumes:
      - static_data:/opt/cd2h-repo-project/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: uwsgi /opt/cd2h-repo-project/var/instance/uwsgi_rest.ini
    image: cd2h-repo-project-web-api
    ports:
      - "5001"
    volumes:
      - static_data:/opt/cd2h-repo-project/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # Task Queue Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "pipenv run celery worker -A invenio_app.celery --loglevel=INFO"
    image: cd2h-repo-project-worker
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
    ports:
      - "6379:6379"
  db:
    extends:
      file: docker-services.yml
      service: db
    ports:
      - "5432:5432"
  mq:
    extends:
      file: docker-services.yml
      service: mq
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    extends:
      file: docker-services.yml
      service: es
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  static_data:
