#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

# Create and install package.json in static folder
invenio npm
STATIC_FOLDER=$(invenio shell --no-term-title -c "print(app.static_folder)")

cd "$STATIC_FOLDER"
npm install
cd -

# Collect and build assets
invenio collect --verbose
invenio assets build
echo "FINISHED BOOTSTRAPPING"
