#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

## Nodejs
# Need to switch node user to root to install globally correctly
npm -g config set user root
npm update
npm install --silent -g node-sass@4.9.0 clean-css@3.4.19 uglify-js@2.7.3 requirejs@2.2.0

CWD=`pwd`
invenio npm
static_folder=$(invenio shell --no-term-title -c "print(app.static_folder)")
cd $static_folder
npm install
cd ${CWD}
invenio collect -v
invenio assets build
