#!/usr/bin/env bash

# Run this script with `pipenv run`, it will destroy the index and repopulate
# it from the DB / data files.
invenio index destroy --force --yes-i-know
invenio index init --force
invenio index reindex --pid-type recid --yes-i-know
invenio index run
menrva terms mesh index
menrva terms fast index
