#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development

# Start Worker
celery worker --app invenio_app.celery --loglevel INFO & process_id_celery=$!

# Start Server
invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key

trap 'kill $process_id_celery &>/dev/null' EXIT

# wait $process_id_celery $process_id_server
