#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 NU,FSM,GHSL.
#
# CD2H Repo Project is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

# Clean redis
invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
# Commented out the below destructive actions for now
# invenio db destroy --yes-i-know
invenio db init create
# invenio index destroy --force --yes-i-know
invenio index init --force
# invenio index queue init purge

# Create SUPER_USER role to give ultimate power
invenio roles create SUPER_USER
invenio access allow superuser-access role SUPER_USER
# ^ This is what makes SUPER_USER all-powerful

# CD2H Repo specific starter setup
## Create location to store files (idempotent)
invenio locations setup_storage
