---
# WARNING: Assume only 1 (non-group) host passed
- hosts: "{{ deploy_host | default('stage')}}"

  tasks:
    - name: docker is installed
      yum:
        name: docker
        state: latest
      become: yes
      tags:
        - docker

    - name: docker-compose is installed and executable
      get_url:
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: u=rwx,g=rx,o=rx
      become: yes

    - name: deploy user is part of dockerroot group
      user:
        name: deploy
        append: yes
        groups: dockerroot
      become: yes

    - name: /etc/docker/daemon.json is configured
      copy:
        src: docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: yes

    - name: docker daemon is enabled and started
      systemd:
        name: docker
        enabled: yes
        state: started
      become: yes

    - name: branch "{{ deploy_branch | default('master')}}" is used
      git:
        repo: git@github.com:galterlibrary/InvenioRDM-at-NU.git
        version: "{{ deploy_branch | default('master')}}"
        dest: cd2h-repo-project
        accept_hostkey: yes
      become: no
      tags:
        - deploy_branch

    - name: server has enough virtual memory for Elasticsearch
      lineinfile:
        path: /etc/sysctl.conf
        line: vm.max_map_count=262144
      become: yes

    # Transfer custom deployment-related files
    - name: cd2h-repo-project/.env is present
      copy:
        src: "{{deploy_host}}.env"
        dest: /home/deploy/cd2h-repo-project/.env
        mode: u=rw,g=r,o=r
      tags:
        - configuration

    - name: cd2h-repo-project/docker/nginx/private.cer is present
      copy:
        src: "{{deploy_host}}.cer"
        dest: /home/deploy/cd2h-repo-project/docker/nginx/private.cer
        mode: u=rw,g=r,o=r
      tags:
        - configuration

    - name: cd2h-repo-project/docker/nginx/private.key is present
      copy:
        src: "{{deploy_host}}.key"
        dest: /home/deploy/cd2h-repo-project/docker/nginx/private.key
        mode: u=rw,g=r,o=r
      tags:
        - configuration

    - name: cd2h-repo-project/docker/haproxy/private.pem is present
      copy:
        src: "{{deploy_host}}.pem"
        dest: /home/deploy/cd2h-repo-project/docker/haproxy/private.pem
        mode: u=rw,g=r,o=r
      tags:
        - configuration

    # Note that this task is long and will always be run right now
    # TODO: Use prebuilt image from registry
    - name: containers are up and running
      command: docker-compose --verbose --file docker-compose.prod.yml up --build --detach
      args:
        chdir: cd2h-repo-project

    - name: one-time scripts/setup was run
      # TODO: have `./scripts/setup` be idempotent
      shell: docker exec cd2h-repo-project_web-ui_1 pipenv run ./scripts/setup && touch setup_was_run.flag
      args:
        creates: setup_was_run.flag
      tags:
        - setup

    - name: update script is run
      # NOTE: update script can only be run now that the containers are up
      #       (dependency on db for instance) and the volumes are mounted
      shell: docker exec cd2h-repo-project_web-ui_1 pipenv run ./scripts/update
